# Generated by Django 3.1 on 2020-08-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_birth', models.TextField()),
                ('employee_department', models.CharField(max_length=100)),
            ],
        ),
    ]
